---
title: "**Análisis y Explotación de la Información**"
subtitle: "CUNEF Universidad"
date: "Página actualizada: `r format.Date(file.mtime('index.Rmd'),'%Y-%m-%d')`"
output:
  html_document:
    css: ./index.css
    toc: yes
    toc_float: yes
    fig_caption: no
    seal : False
    includes:
      after_body: insert-logo.html
  pdf_document:
    toc: yes
---


<div class="title-logo"></div>

```{r packages_setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
knitr::opts_chunk$set(fig.width=8, fig.height=6) 
```

<br />

Bienvenido al sitio web de la asignatura de **Análisis y Explotación de la Información** del primer cuatrimestre del curso 2025-2026 en CUNEF Universidad. En este sitio web encontrarás el material y los laboratorios que usaremos durante el curso. La página se actualizará con frecuencia durante el cuatrimestre, así que acostúmbrate a visitarla a menudo.

## **Contenido**

### Tema 0 : Introducción
  - [Diapositivas](./topic0/topic0.html)



### Tema 1 : Programación en R
  - [Diapositivas](./topic1/topic1.html)


### Tema 2 : Análisis Exploratorio de los Datos
- 2.1: Visualización de datos
  - [Diapositivas](./topic2/topic2-1.html)


- 2.2: Transformación de datos
  - [Diapositivas](./topic2/topic2-2.html)


- 2.3: Análisis Exploratorio de datos
  - [Diapositivas](./topic2/topic2-3.html)
 

### Tema 3 : Data Wrangling

  - 3.1: Importación de datos
    - [Diapositivas](./topic3/topic3-1.html)


  - 3.2: Organización de datos
    - [Diapositivas](./topic3/topic3-2.html)

 
  - 3.3: Transformación de datos
    - [Diapositivas](./topic3/topic3-3.html)


### Tema 4 : Modelización
  - [Diapositivas](./topic4/topic4.html)

 
### Tema 5 : Comunicación de Resultados
  - [Diapositivas](./topic5/topic5.html)
  



## **Laboratorios**


### Lab 1 - Programación en R 
  - [Ejercicios](./labs/lab1.html)


### Lab 2.1 - Visualización 
  - [Ejercicios](./labs/lab2.html)
  

### Lab 2.2 - Transformación
  - [Ejercicios](./labs/lab3.html)
  

### Lab 3.1 - Importación
  - [Ejercicios](./labs/lab4.html)


### Lab 3.2 - Data Wrangling
  - [Ejercicios](./labs/lab5.html)


### Lab 3.3 - Strings, Factores y Fechas
  - [Ejercicios](./labs/lab6.html)


### Lab 4 - Modelos
  - [Ejercicios](./labs/lab7.html)

